
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: info
  path: f:/code/


jedis :
  pool :
    host : 192.168.56.104
    port : 6379
    timeout: 1000
    password: 123456
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000