spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill_boot
    username: root
    password: root
  output:
    ansi:
      enabled: detect
  redis:
    database: 0
    host: 192.168.56.104
    port: 6379
    password: 123456
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

mybatis:
  type-aliases-package: com.github.congyh.seckill.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    database-id: mysql
server:
  port: 8081



